dist: bionic

language: rust

services:
  - docker

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libssl-dev libostree-dev

deploy:
  provider: script
  script: ./.travis/docker-push
  on:
    branch: feature/fasterci
    condition: $TRAVIS_RUST_VERSION = stable

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
